language: go
go:
  - 1.3
  - tip

script:
  - go build
  - go test -v
  - go test -v -tags=integration

notifications:
  slack:
    secure: YyKza3/7/PKJ5b+zIffDS0WNCdW03zBWg1A/ABqIXcR+sqkYJcaKVOg/PpfmliV3DMTg5Hkbegx4DI+O/zjGMP4v0dPjxK7jS4fkHRdlh4nocJWoxWJvLMWnGy1HnxIBhEWBwWlsgyTMb4ujujzbCk+4M25xKP+WHP+cAQtfTxQF9beZOjTzWENaIoW5SweV0RrtKrLkDROol4XWoRZF2vtMfemu/ovEEZ+u9o793SNceYtYjjM2X2MtBWpb0xoktBo0yy12zbjKaPjId34zF6PoED4sxhqSsl7jTEP4H1WAEFBzbGGqR0ewpJ4dhzbL1g2SF8RKtAlpv7NjZ1504e2R+rnis7fLaSyy5ZlMYIyeEpnYYcw6bUtBlApsBuwjl51FGBpygKzznWRERl/poDJ27kluQmVBmoS6OHXRpQs6PV0YXrv9nC8iz3tG5zfPNJQ0PvVQi3j6poET5/fal1inq+/cFWnyDpByCKhcq3V0r9atYDzvn2pz7Ebxt3Xrlzf4c5cz6iQ7KP7CJ4UHs0F37Y31FBuxLx73eye7iHAiYJms/mjAM80ykOqk4aKY7/AHrDOzsHPP/A2VZP8KGOiK6PJ0MUM/KSzHovaS7dLEq/Z73c4SuXdQiST9AYLZF3anbmpu+5Aw4CRq6zE6g3xUS55drgja5YF4nI/ujWI=
